### ISSUE TITLE
Cannot continue when replace parameter name.

### ISSUE THREAD

**Issue by CaijiOrz** [LogicalTrust/BurpSessionHandlingMatchReplace#1]
Hi.

I have encountered an alternative CSRF_Token that uses a random name and a random value as CSRF_Token.
For example: &aW6MMNQzhb5kMpb=Tmz1KPcngAD1Nwt7

I thought of a way to use a macro to extract the random name and value, name=1&value=1, then replace &name= with null, and &value= with =, to implement CSRF_Token like that.

Until I found out your plugin, unfortunately it can only be replaced by the parameter name. If any character is specified, it will stop running. Can you help me and continue to optimize this plugin?

Replace any character, not just paremeters.

**Comment by mmmds** [comment]
Hi,

I'm not sure that I understand your problem. Let's say that I have a request with body:
aaa=1&bbb=2&ccc=3
then I set up in the extension
match: &bbb=2
replace: &YYY=9
then the request's body is modified by the extension to:
aaa=1&YYY=9&ccc=3

If it does not solve your problem please give a specific example.

**Comment by CaijiOrz** [comment]
Sorry, it is too complicated for me to describe.

example:
username=admin&password=admin&name=RbuCE1mUDnlUf24&value=QtF9TG4AUMtDAc1

I want:
username=admin&password=admin&RbuCE1mUDnlUf24=QtF9TG4AUMtDAc1

I set up in the exxtension:
1. 
match: &name=
replace: &
2.
match: &value=
replace: =

But when I make a request, I can't continue, and the status is always waiting.

You can try again.
